-- First, let's populate the insurers table with Nigerian insurance companies
INSERT INTO public.insurers (organization_id, name, email, phone, address, specialties, rating, performance_score, is_active) VALUES
-- Get a sample organization_id first - we'll need to update this query to use actual org IDs
((SELECT id FROM public.organizations LIMIT 1), 'AIICO Insurance Plc', 'info@aiicoplc.com', '+234-1-2701030', 'AIICO Plaza, Plot PC 12, Afribank Street, Victoria Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'General', 'Life'], 4.2, 85, true),
((SELECT id FROM public.organizations LIMIT 1), 'Leadway Assurance Company Limited', 'info@leadway.com.ng', '+234-1-2800800', 'Leadway House, 1 Mekunwen Road, Ikoyi, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'Aviation', 'Engineering'], 4.0, 82, true),
((SELECT id FROM public.organizations LIMIT 1), 'AXA Mansard Insurance Plc', 'customerservice@axamansard.com', '+234-1-2716905', 'AXA Mansard House, 1684, Sanusi Fafunwa Street, Victoria Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'Aviation', 'Life', 'Health'], 4.5, 90, true),
((SELECT id FROM public.organizations LIMIT 1), 'Cornerstone Insurance Plc', 'info@cornerstoneinsurance.com.ng', '+234-1-4488482', 'Universal Insurance Building, 119, Awolowo Road, Ikoyi, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'General'], 3.8, 78, true),
((SELECT id FROM public.organizations LIMIT 1), 'Sovereign Trust Insurance Plc', 'info@sovereigntrustinsurance.com.ng', '+234-1-2806881', 'Baico Plaza, 12th Floor, 12, Abibu Oki Street, Lagos Island, Lagos', ARRAY['Motor', 'Fire', 'Engineering', 'Aviation'], 3.9, 80, true),
((SELECT id FROM public.organizations LIMIT 1), 'LASACO Assurance Plc', 'info@lasaco.com.ng', '+234-1-7747014', 'LASACO Building, 62, Adeniji Adele Road, Lagos Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'General'], 3.7, 75, true),
((SELECT id FROM public.organizations LIMIT 1), 'Consolidated Hallmark Insurance Plc', 'info@consolidatedhallmark.com', '+234-1-2808160', 'Reinsurance House, 784A, Herbert Macaulay Way, Central Business District, Abuja', ARRAY['Motor', 'Fire', 'Marine', 'Oil & Gas'], 4.1, 83, true),
((SELECT id FROM public.organizations LIMIT 1), 'Guinea Insurance Plc', 'info@guineainsurance.com.ng', '+234-1-2660678', 'Guinea House, 51/55, Broad Street, Lagos Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'General'], 3.6, 72, true),
((SELECT id FROM public.organizations LIMIT 1), 'Great Nigeria Insurance Plc', 'info@greatnigeria.com.ng', '+234-1-2664561', 'Great Nigeria House, 206, Awolowo Road, Ikoyi, Lagos', ARRAY['Motor', 'Fire', 'Engineering', 'Aviation'], 3.9, 79, true),
((SELECT id FROM public.organizations LIMIT 1), 'Niger Insurance Plc', 'info@nigerinsurance.com.ng', '+234-1-2663100', 'Niger House, 302, Ikorodu Road, Anthony, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'General'], 3.8, 77, true),
((SELECT id FROM public.organizations LIMIT 1), 'Royal Exchange Assurance Plc', 'info@royalexchangeplc.com', '+234-1-2664081', 'Royal Exchange House, 31, Marina, Lagos Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'Life'], 4.0, 81, true),
((SELECT id FROM public.organizations LIMIT 1), 'Standard Alliance Insurance Plc', 'info@standardalliance.com.ng', '+234-1-2702886', 'Standard Alliance House, 32, Moloney Street, Ikoyi, Lagos', ARRAY['Motor', 'Fire', 'General', 'Health'], 3.7, 74, true),
((SELECT id FROM public.organizations LIMIT 1), 'Veritas Kapital Assurance Plc', 'info@veritaskapital.com', '+234-1-2805646', 'Veitas House, 13A, Bishop Oluwole Street, Victoria Island, Lagos', ARRAY['Motor', 'Fire', 'Marine', 'Professional Indemnity'], 3.9, 78, true),
((SELECT id FROM public.organizations LIMIT 1), 'Unity Kapital Assurance Plc', 'info@unitykapital.com.ng', '+234-1-2805220', 'Unity Kapital House, 7th Floor, 117, Broad Street, Lagos Island, Lagos', ARRAY['Motor', 'Fire', 'General'], 3.6, 73, true),
((SELECT id FROM public.organizations LIMIT 1), 'Mutual Benefits Assurance Plc', 'info@mutualng.com', '+234-1-2805499', 'Mutual Benefits House, 78, Kofo Abayomi Street, Victoria Island, Lagos', ARRAY['Motor', 'Fire', 'Life', 'Health'], 4.0, 80, true)
ON CONFLICT (organization_id, name) DO NOTHING;