-- Insert Nigerian insurance companies into the insurers table
INSERT INTO public.insurers (organization_id, name, email, phone, address, specialties, rating, performance_score, is_active) VALUES
-- Get the first organization ID from organizations table for demo purposes
((SELECT id FROM public.organizations LIMIT 1), 'AIICO Insurance Plc', 'info@aiicoplc.com', '+234-1-2793740', '29 Asa Afariogun Street, Ajao Estate, Lagos', ARRAY['Life', 'General', 'Motor', 'Fire', 'Marine'], 4.2, 85, true),
((SELECT id FROM public.organizations LIMIT 1), 'Leadway Assurance Company Limited', 'info@leadway.com.ng', '+234-708-060-6000', '1 Mekunwen Road, Brikon, Lagos', ARRAY['Life', 'General', 'Motor', 'Fire', 'Health'], 4.5, 90, true),
((SELECT id FROM public.organizations LIMIT 1), 'AXA Mansard Insurance Plc', 'info@axamansard.com', '+234-1-2701653', '1684 Sanusi Fafunwa Street, Victoria Island, Lagos', ARRAY['General', 'Life', 'Motor', 'Fire', 'Marine', 'Aviation'], 4.3, 88, true),
((SELECT id FROM public.organizations LIMIT 1), 'Custodian Investment Plc', 'info@custodianplc.com', '+234-1-4488200', '14 Keffi Street, South West Ikoyi, Lagos', ARRAY['Life', 'General', 'Motor', 'Fire'], 4.1, 82, true),
((SELECT id FROM public.organizations LIMIT 1), 'Cornerstone Insurance Plc', 'info@cornerstone.com.ng', '+234-1-2808282', '136 Lewis Street, Lagos Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Marine', 'Engineering'], 4.0, 80, true),
((SELECT id FROM public.organizations LIMIT 1), 'Continental Reinsurance Plc', 'info@continentalre.com', '+234-1-4626650', '23 Idowu Taylor Street, Victoria Island, Lagos', ARRAY['General', 'Life', 'Fire', 'Marine', 'Aviation', 'Oil & Gas'], 4.4, 87, true),
((SELECT id FROM public.organizations LIMIT 1), 'NICON Insurance Corporation', 'info@niconinsurance.com', '+234-9-2344072', 'NICON House, Plot 242 Muhammadu Buhari Way, Central Business District, Abuja', ARRAY['General', 'Life', 'Motor', 'Fire', 'Marine'], 3.9, 78, true),
((SELECT id FROM public.organizations LIMIT 1), 'Guinea Insurance Plc', 'info@guineainsurance.com.ng', '+234-1-2601160', '46 Marina, Lagos Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Marine'], 3.8, 75, true),
((SELECT id FROM public.organizations LIMIT 1), 'Regency Alliance Insurance Plc', 'info@regencyalliance.com', '+234-1-7746290', '35 Kofo Abayomi Street, Victoria Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Engineering'], 3.7, 73, true),
((SELECT id FROM public.organizations LIMIT 1), 'Standard Alliance Insurance Plc', 'info@sai.com.ng', '+234-1-4628290', '13 Akin Adesola Street, Victoria Island, Lagos', ARRAY['General', 'Life', 'Motor', 'Fire', 'Health'], 4.0, 81, true),
((SELECT id FROM public.organizations LIMIT 1), 'Sovereign Trust Insurance Plc', 'info@sovereigntrust.com.ng', '+234-1-4488482', '27 Obafemi Awolowo Way, Ikeja, Lagos', ARRAY['General', 'Motor', 'Fire', 'Marine'], 3.9, 77, true),
((SELECT id FROM public.organizations LIMIT 1), 'Mutual Benefits Assurance Plc', 'info@mutualng.com', '+234-1-2800770', '3rd Floor, Stallion Plaza, 36 Marina, Lagos', ARRAY['Life', 'General', 'Motor', 'Fire', 'Health'], 3.8, 76, true),
((SELECT id FROM public.organizations LIMIT 1), 'Prestige Assurance Plc', 'info@prestigeassurance.com', '+234-1-2601160', '19 Kakawa Street, Lagos Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Marine'], 3.6, 72, true),
((SELECT id FROM public.organizations LIMIT 1), 'Consolidated Hallmark Insurance Plc', 'info@chi.com.ng', '+234-1-2713817', '21 Akin Adesola Street, Victoria Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Engineering'], 3.9, 79, true),
((SELECT id FROM public.organizations LIMIT 1), 'NEM Insurance Company (Nig) Plc', 'info@neminsurance.com.ng', '+234-1-2646794', '142 Ahmadu Bello Way, Victoria Island, Lagos', ARRAY['General', 'Motor', 'Fire', 'Marine', 'Aviation'], 4.1, 83, true);