// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugncehdwghhampoxmfwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbmNlaGR3Z2hoYW1wb3htZnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDE1ODUsImV4cCI6MjA2NTUxNzU4NX0.eGCky5BGxaDn-cDt1qpyxIuQKFDZwp6x4zCgh2LnWz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);